version: '3.9'

services:
  postgres:
    image: postgres
    container_name: dotshop_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rand0mPassword
      POSTGRES_DB: dotshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  
  redis:
    image: redis
    container_name: dotshop_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=rand0mPassword
      - REDIS_PORT=6379
      - REDIS_DATABASE=16
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
